<?php

namespace ContainerO5KS4Xl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SOaaWJRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sOaaWJR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sOaaWJR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', 'App\\Request\\PetCreationRequest', NULL, 'Cannot autowire service "App\\Request\\PetCreationRequest": argument "$petName" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'request' => 'App\\Request\\PetCreationRequest',
        ]);
    }
}
