<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXe3MRy4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXe3MRy4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXe3MRy4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXe3MRy4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXe3MRy4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xe3MRy4',
    'container.build_id' => '0aeb1c6c',
    'container.build_time' => 1705930406,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXe3MRy4');
